AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura LDAP completa - Servidor, Cliente y LAM'

Parameters:
  KeyName:
    Description: Nombre de un key pair EC2 existente
    Type: 'AWS::EC2::KeyPair::KeyName'

  InstanceType:
    Description: Tipo de instancia EC2
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small

  GitHubRawURL:
    Description: URL RAW del repositorio GitHub con los scripts
    Type: String
    Default: 'https://raw.githubusercontent.com/Janics22/ldapAWS/main'

Resources:

  LDAPSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group para servidores LDAP
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 22,  ToPort: 22,  CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 80,  ToPort: 80,  CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 443, ToPort: 443, CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 389, ToPort: 389, CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 636, ToPort: 636, CidrIp: 0.0.0.0/0 }

  # =============================
  # SERVIDOR LDAP
  # =============================
  LDAPServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0fa3fe0fa7920f68e
      SecurityGroupIds: [ !GetAtt LDAPSecurityGroup.GroupId ]
      Tags:
        - Key: Name
          Value: ldap-server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          exec > >(tee /var/log/user-data.log) 2>&1

          dnf update -y
          dnf install -y nc

          echo "[INFO] Descargando server_ldap.sh"
          cd /tmp
          curl -L -o server_ldap.sh "${GitHubRawURL}/server_ldap.sh"
          chmod +x server_ldap.sh

          echo "[INFO] Ejecutando script servidor LDAP"
          /tmp/server_ldap.sh

          echo "[INFO] Servidor LDAP instalado"

  # =============================
  # CLIENTE LDAP
  # =============================
  LDAPClient:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0fa3fe0fa7920f68e
      SecurityGroupIds: [ !GetAtt LDAPSecurityGroup.GroupId ]
      Tags:
        - Key: Name
          Value: ldap-client
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          exec > >(tee /var/log/user-data.log) 2>&1

          dnf update -y
          dnf install -y nc

          echo "[INFO] Esperando servidor LDAP en ${LDAPServer.PrivateIp}:389"

          for i in {1..30}; do
              if nc -z ${LDAPServer.PrivateIp} 389; then
                  echo "[INFO] Servidor LDAP disponible"
                  break
              fi
              echo "[WARN] Servidor aún no responde, reintentando..."
              sleep 10
          done

          cd /tmp
          curl -L -o client_ldap.sh "${GitHubRawURL}/client_ldap.sh"
          chmod +x client_ldap.sh

          echo "[INFO] Ejecutando script cliente LDAP"
          /tmp/client_ldap.sh ${LDAPServer.PrivateIp}

          echo "[INFO] Cliente LDAP configurado"

  # =============================
  # ZONA PRIVADA DE DNS PARA LDAP
  # =============================
  LDAPPrivateHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: ldap.local
      VPCs:
        - VPCId: !Ref "AWS::StackName" # Aquí se reemplaza con la VPC donde están tus instancias
          VPCRegion: !Ref "AWS::Region"
      HostedZoneConfig:
        Comment: "Zona privada para resolver ldap-server dentro de la VPC"

  LDAPServerDNSRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref LDAPPrivateHostedZone
      Name: ldap-server.ldap.local
      Type: A
      TTL: '300'
      ResourceRecords:
        - !GetAtt LDAPServer.PrivateIp

  # =============================
  # SERVIDOR LAM
  # =============================
  LAMServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0fa3fe0fa7920f68e
      SecurityGroupIds: [ !GetAtt LDAPSecurityGroup.GroupId ]
      Tags:
        - Key: Name
          Value: ldap-lam
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          exec > >(tee /var/log/user-data.log) 2>&1

          dnf update -y
          dnf install -y nc

          echo "[INFO] Esperando servidor LDAP en ${LDAPServer.PrivateIp}:389"

          for i in {1..30}; do
              if nc -z ${LDAPServer.PrivateIp} 389; then
                  echo "[INFO] Servidor LDAP disponible"
                  break
              fi
              echo "[WARN] Servidor aún no responde, reintentando..."
              sleep 10
          done

          cd /tmp
          curl -L -o lam.sh "${GitHubRawURL}/lam.sh"
          chmod +x lam.sh

          echo "[INFO] Ejecutando script LAM"
          /tmp/lam.sh ${LDAPServer.PrivateIp}

          echo "[INFO] LAM instalado"

  

Outputs:

  LDAPServerIP:
    Value: !GetAtt LDAPServer.PublicIp

  LDAPClientIP:
    Value: !GetAtt LDAPClient.PublicIp

  LAMServerIP:
    Value: !GetAtt LAMServer.PublicIp

  LAMURL:
    Value: !Sub "http://${LAMServer.PublicIp}/lam"

  AccessInfo:
    Value: !Sub |
      LAM: http://${LAMServer.PublicIp}/lam
      Usuario: cn=admin,dc=amsa,dc=udl,dc=cat
      Password: 1234

  SecurityGroupId:
    Value: !GetAtt LDAPSecurityGroup.GroupId



